param(
    [string]$RawDir = "sources/raw",
    [string]$OutputPath = "sources/study-queue.generated.md",
    [datetime]$Category4CreatedAfter = "2024-01-01",
    [int]$MaxItemsPerTopic = 80
)

$ErrorActionPreference = "Stop"

$topicRules = @(
    [pscustomobject]@{ name = "tutorial"; keywords = @("tutorial", "guide", "how", "use", "beginner", "newbie", "jiaocheng", "rumen") },
    [pscustomobject]@{ name = "code-js-expression"; keywords = @("code", "source", "js", "javascript", "expr", "expression", "function", "var", "variable") },
    [pscustomobject]@{ name = "ocr-image-color-coordinate"; keywords = @("ocr", "recognition", "image", "color", "multi-color", "coordinate", "screenshot") },
    [pscustomobject]@{ name = "flow-condition-listener"; keywords = @("flow", "condition", "jump", "loop", "listener", "wait", "retry", "timer") },
    [pscustomobject]@{ name = "file-api-network-log"; keywords = @("file", "log", "api", "request", "upload", "download", "json", "txt", "http") },
    [pscustomobject]@{ name = "backend-deploy-hot-update-license"; keywords = @("backend", "server", "deploy", "hot", "update", "license", "auth", "supabase", "mongo", "express", "php") },
    [pscustomobject]@{ name = "environment-permission-emulator"; keywords = @("environment", "permission", "accessibility", "emulator", "redfinger", "mumu", "android", "stuck", "black") },
    [pscustomobject]@{ name = "ui-dialog-markdown"; keywords = @("ui", "dialog", "markdown", "config", "setting", "table", "page", "button") },
    [pscustomobject]@{ name = "video-attachment-link"; keywords = @("video", "recording", "attachment", "download", "github", "gitee", "link") }
)

function Get-Prop {
    param([object]$Object, [string]$Name)
    if ($null -eq $Object) { return $null }
    if ($Object -is [System.Collections.IDictionary]) {
        if ($Object.Contains($Name)) { return $Object[$Name] }
        return $null
    }
    $prop = $Object.PSObject.Properties[$Name]
    if ($null -ne $prop) { return $prop.Value }
    return $null
}

function Get-Nested {
    param([object]$Object, [string]$Path)
    $current = $Object
    foreach ($part in $Path.Split(".")) {
        $current = Get-Prop -Object $current -Name $part
        if ($null -eq $current) { return $null }
    }
    return $current
}

function Get-FirstValue {
    param([object]$Object, [string[]]$Names)
    foreach ($name in $Names) {
        $value = Get-Nested -Object $Object -Path $name
        if ($null -ne $value -and "$value" -ne "") { return $value }
    }
    return $null
}

function Get-FirstArray {
    param([object]$Object, [string[]]$Paths)
    foreach ($path in $Paths) {
        $value = Get-Nested -Object $Object -Path $path
        if ($null -eq $value) { continue }
        if ($value -is [array]) { return @($value) }
        if ($value -is [System.Collections.IEnumerable] -and -not ($value -is [string])) { return @($value) }
    }
    return @()
}

function Convert-ForumDate {
    param([object]$Value)
    if ($null -eq $Value -or "$Value" -eq "") { return $null }
    try {
        if ($Value -is [int] -or $Value -is [long] -or "$Value" -match '^\d+$') {
            $number = [int64]$Value
            if ($number -gt 999999999999) {
                return [DateTimeOffset]::FromUnixTimeMilliseconds($number).LocalDateTime
            }
            return [DateTimeOffset]::FromUnixTimeSeconds($number).LocalDateTime
        }
        return [datetime]::Parse("$Value")
    }
    catch {
        return $null
    }
}

function Get-TopicTags {
    param([string]$Text)
    $lower = "$Text".ToLowerInvariant()
    $tags = @()
    foreach ($rule in $topicRules) {
        foreach ($keyword in $rule.keywords) {
            if ($lower.Contains($keyword.ToLowerInvariant())) {
                $tags += $rule.name
                break
            }
        }
    }
    if ($tags.Count -eq 0) { return @("manual-review") }
    return @($tags | Sort-Object -Unique)
}

function Get-IdsFromCoverageBlock {
    param([string]$CoverageText, [int]$BlockIndex)
    $blocks = @([regex]::Matches($CoverageText, '~~~text\s*([\s\S]*?)~~~'))
    if ($blocks.Count -le $BlockIndex) { return @() }
    return @([regex]::Matches($blocks[$BlockIndex].Groups[1].Value, '\b\d+\b') | ForEach-Object { [int]$_.Value })
}

function Add-Line {
    param([System.Collections.Generic.List[string]]$Lines, [string]$Text = "")
    $Lines.Add($Text) | Out-Null
}

$lines = New-Object System.Collections.Generic.List[string]
Add-Line $lines "# ZDJL study queue"
Add-Line $lines
Add-Line $lines "Generated at: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
Add-Line $lines
Add-Line $lines "Generated by tools/build-study-queue.ps1. This is a work queue, not proof of completion."
Add-Line $lines

$allItems = New-Object System.Collections.Generic.List[object]

if (Test-Path -LiteralPath $RawDir) {
    $pageFiles = Get-ChildItem -LiteralPath $RawDir -Recurse -File -Filter "page-*.json" | Sort-Object FullName
    foreach ($file in $pageFiles) {
        try {
            $json = Get-Content -Raw -Encoding utf8 -LiteralPath $file.FullName | ConvertFrom-Json
            $categoryMatch = [regex]::Match($file.FullName, 'category-(\d+)')
            $categoryId = if ($categoryMatch.Success) { [int]$categoryMatch.Groups[1].Value } else { 0 }
            $items = Get-FirstArray -Object $json -Paths @("data.list", "data.threads", "data.items", "data.rows", "list", "threads", "items", "rows")
            foreach ($item in $items) {
                $id = Get-FirstValue -Object $item -Names @("id", "thread_id", "threadId")
                if ($null -eq $id -or "$id" -notmatch '^\d+$') { continue }
                $title = Get-FirstValue -Object $item -Names @("title", "subject", "name")
                $summary = Get-FirstValue -Object $item -Names @("summary", "content", "message", "description", "excerpt")
                $createdAt = Convert-ForumDate (Get-FirstValue -Object $item -Names @("created_at", "createdAt", "create_time", "created"))
                $postedAt = Convert-ForumDate (Get-FirstValue -Object $item -Names @("posted_at", "postedAt", "updated_at", "updatedAt", "last_posted_at"))
                $text = "$title $summary"
                $tags = Get-TopicTags -Text $text
                $include = $true
                if ($categoryId -eq 4 -and ($null -eq $createdAt -or $createdAt -lt $Category4CreatedAfter)) {
                    $include = $false
                }
                $allItems.Add([pscustomobject]@{
                    category_id = $categoryId
                    id = [int]$id
                    title = "$title"
                    created_at = if ($createdAt) { $createdAt.ToString("yyyy-MM-dd") } else { "" }
                    posted_at = if ($postedAt) { $postedAt.ToString("yyyy-MM-dd") } else { "" }
                    include = $include
                    tags = @($tags)
                    source = $file.FullName
                })
            }
        }
        catch {
            Add-Line $lines "- Failed to read $($file.FullName): $($_.Exception.Message)"
        }
    }
}

if ($allItems.Count -gt 0) {
    $unique = @{}
    foreach ($item in $allItems) {
        $key = "$($item.category_id)-$($item.id)"
        $unique[$key] = $item
    }
    $items = @($unique.Values | Sort-Object category_id, id)
    $included = @($items | Where-Object { $_.include })

    Add-Line $lines "## Raw data summary"
    Add-Line $lines
    Add-Line $lines "| Item | Count |"
    Add-Line $lines "|---|---:|"
    Add-Line $lines "| Unique raw threads | $($items.Count) |"
    Add-Line $lines "| Included for deep-read | $($included.Count) |"
    Add-Line $lines "| Excluded by rule | $($items.Count - $included.Count) |"
    Add-Line $lines

    foreach ($categoryId in @(3, 4)) {
        $categoryItems = @($included | Where-Object { $_.category_id -eq $categoryId })
        if ($categoryItems.Count -eq 0) { continue }
        Add-Line $lines "## Category $categoryId queue"
        Add-Line $lines
        Add-Line $lines "| Thread ID | Created | Tags | Title |"
        Add-Line $lines "|---:|---|---|---|"
        foreach ($item in $categoryItems) {
            $tagText = ($item.tags -join ", ").Replace("|", "/")
            $title = ($item.title -replace '\|', '/')
            Add-Line $lines "| $($item.id) | $($item.created_at) | $tagText | [$title](https://bbs.zdjl.site/#/thread/detail/$($item.id)) |"
        }
        Add-Line $lines
    }

    Add-Line $lines "## Topic candidates"
    Add-Line $lines
    foreach ($rule in $topicRules) {
        $topicItems = @($included | Where-Object { $_.tags -contains $rule.name } | Select-Object -First $MaxItemsPerTopic)
        if ($topicItems.Count -eq 0) { continue }
        Add-Line $lines "### $($rule.name)"
        Add-Line $lines
        foreach ($item in $topicItems) {
            Add-Line $lines "- Category $($item.category_id) / $($item.id): [$($item.title)](https://bbs.zdjl.site/#/thread/detail/$($item.id))"
        }
        Add-Line $lines
    }
}
else {
    Add-Line $lines "## No usable raw JSON yet"
    Add-Line $lines
    Add-Line $lines "No valid forum sync output was found under $RawDir. Falling back to the existing category 3 coverage table."
    Add-Line $lines

    $coveragePath = "sources/category-3-topic-coverage.md"
    if (Test-Path -LiteralPath $coveragePath) {
        $coverage = Get-Content -Raw -Encoding utf8 -LiteralPath $coveragePath
        $doneIds = Get-IdsFromCoverageBlock -CoverageText $coverage -BlockIndex 0
        $sourceOnlyIds = Get-IdsFromCoverageBlock -CoverageText $coverage -BlockIndex 1
        $queuedIds = Get-IdsFromCoverageBlock -CoverageText $coverage -BlockIndex 2

        Add-Line $lines "| Category 3 state | Count |"
        Add-Line $lines "|---|---:|"
        Add-Line $lines "| Already in topic notes | $($doneIds.Count) |"
        Add-Line $lines "| Source-summary only | $($sourceOnlyIds.Count) |"
        Add-Line $lines "| Not yet specialized | $($queuedIds.Count) |"
        Add-Line $lines

        if ($sourceOnlyIds.Count -gt 0) {
            Add-Line $lines "### Priority source-00"
            Add-Line $lines
            foreach ($id in $sourceOnlyIds) {
                Add-Line $lines "- ${id}: [source](https://bbs.zdjl.site/#/thread/detail/$id)"
            }
            Add-Line $lines
        }

        Add-Line $lines "### First 40 unspecialized threads"
        Add-Line $lines
        foreach ($id in ($queuedIds | Select-Object -First 40)) {
            Add-Line $lines "- ${id}: [source](https://bbs.zdjl.site/#/thread/detail/$id)"
        }
    }
    else {
        Add-Line $lines "Missing $coveragePath. Build category 3 coverage first."
    }
}

$parent = Split-Path -Parent $OutputPath
if ($parent -and -not (Test-Path -LiteralPath $parent)) {
    New-Item -ItemType Directory -Path $parent | Out-Null
}
Set-Content -LiteralPath $OutputPath -Value ($lines -join [Environment]::NewLine) -Encoding utf8

[ordered]@{
    output = $OutputPath
    raw_dir = $RawDir
    generated_at = (Get-Date).ToString("s")
    raw_items_seen = $allItems.Count
} | ConvertTo-Json -Depth 5
